$(function()
			    {
			    	$("#bg1").click(function()
			    	{
			    		$("#bgimg2").attr("src","img/hf2.jpg");
			    		$("#bgimg3").attr("src","img/hf3.jpg");
			    		$("#bgimg4").attr("src","img/hf4.jpg");
			    		$("#bgimg5").attr("src","img/hf5.jpg");
			    		$("#bgimg6").attr("src","img/hf6.jpg");
			    		$("#topbg").css("background","url(img/hf1.jpg)");
			    		$("#bgimg1").attr("src","img/hfok1.jpg");
			    	});
			    	$("#bg2").click(function()
			    	{
			    		$("#bgimg1").attr("src","img/hf1.jpg");
			    		$("#bgimg3").attr("src","img/hf3.jpg");
			    		$("#bgimg4").attr("src","img/hf4.jpg");
			    		$("#bgimg5").attr("src","img/hf5.jpg");
			    		$("#bgimg6").attr("src","img/hf6.jpg");
			    		$("#topbg").css("background","url(img/hf2.jpg)");
			    		$("#bgimg2").attr("src","img/hfok2.jpg");
			    	});
			    	$("#bg3").click(function()
			    	{
			    		$("#bgimg1").attr("src","img/hf1.jpg");
			    		$("#bgimg2").attr("src","img/hf2.jpg");
			    		$("#bgimg4").attr("src","img/hf4.jpg");
			    		$("#bgimg5").attr("src","img/hf5.jpg");
			    		$("#bgimg6").attr("src","img/hf6.jpg");
			    		$("#topbg").css("background","url(img/hf3.jpg)");
			    		$("#bgimg3").attr("src","img/hfok3.jpg");
			    	});
			    	$("#bg4").click(function()
			    	{
			    		$("#bgimg1").attr("src","img/hf1.jpg");
			    		$("#bgimg2").attr("src","img/hf2.jpg");
			    		$("#bgimg3").attr("src","img/hf3.jpg");
			    		$("#bgimg5").attr("src","img/hf5.jpg");
			    		$("#bgimg6").attr("src","img/hf6.jpg");
			    		$("#topbg").css("background","url(img/hf4.jpg)");
			    		$("#bgimg4").attr("src","img/hfok4.jpg");
			    	});
			    	$("#bg5").click(function()
			    	{
			    		$("#bgimg1").attr("src","img/hf1.jpg");
			    		$("#bgimg3").attr("src","img/hf3.jpg");
			    		$("#bgimg4").attr("src","img/hf4.jpg");
			    		$("#bgimg2").attr("src","img/hf2.jpg");
			    		$("#bgimg6").attr("src","img/hf6.jpg");
			    		$("#topbg").css("background","url(img/hf5.jpg)");
			    		$("#bgimg5").attr("src","img/hfok5.jpg");
			    	});
			    	$("#bg6").click(function()
			    	{
			    		$("#bgimg1").attr("src","img/hf1.jpg");
			    		$("#bgimg3").attr("src","img/hf3.jpg");
			    		$("#bgimg4").attr("src","img/hf4.jpg");
			    		$("#bgimg5").attr("src","img/hf5.jpg");
			    		$("#bgimg2").attr("src","img/hf2.jpg");
			    		$("#topbg").css("background","url(img/hf6.jpg)");
			    		$("#bgimg6").attr("src","img/hfok6.jpg");
			    	});
			    });